using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RB_Website_API.Models;

[Table("LoanApplications", Schema = "dbo")]
public sealed class LoanApplication
{
    /// <summary>Same as RBMAIN.dbo.lead_data.Lead_id — not generated by MBM.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    [MaxLength(160)]
    public string FullName { get; set; } = "";

    [MaxLength(10)]
    public string Phone { get; set; } = "";

    [MaxLength(508)]
    public string? Email { get; set; }

    [MaxLength(6)]
    public string Pincode { get; set; } = "";

    public int LoanTypeId { get; set; }

    public long LoanAmount { get; set; }

    public bool ConsentAccepted { get; set; }

    public DateTime? ConsentAcceptedAt { get; set; }

    public DateTime CreatedAt { get; set; }
}
